name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build  # Using 'build' to compile and run tests for all modules

    # Optional: Upload APK if needed (example for debug APK)
    # - name: Upload Debug APK
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: app-debug-apk
    #     path: app/build/outputs/apk/debug/app-debug.apk # Adjust path as necessary
    #     if-no-files-found: error # Fails the workflow if the APK is not found.
